{% set name = "whos-there" %}
{% set version = "0.6.0" %}

# Alternative recipe that avoids uv-dynamic-versioning if needed
# This uses the wheel from PyPI instead of building from source

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Using the wheel instead of sdist
  url: https://files.pythonhosted.org/packages/py3/w/whos_there/whos_there-{{ version }}-py3-none-any.whl
  sha256: fcb43ce2520f1ee13b7bb7614d4a6ffff4ae4acc1cb24a77378f89c78fea5a3c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-index whos_there-{{ version }}-py3-none-any.whl

requirements:
  host:
    - pip
    - python >=3.11
  run:
    - python >=3.11
    - lightning >=2.6.1
    - python-telegram-bot >=22.6
    - requests >=2.32.5

test:
  imports:
    - whos_there
    - whos_there.senders
    - whos_there.callback
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://twsl.github.io/whos-there/
  summary: The spiritual successor to knockknock for PyTorch Lightning, get notified when your training ends
  license: MIT
  license_file: LICENSE
  description: |
    The spiritual successor to knockknock for PyTorch Lightning, 
    get notified when your training is complete or when it crashes during the 
    process with a single callback.

    ## Features

    - Supports E-Mail, Discord, Slack, Teams, Telegram
  doc_url: https://twsl.github.io/whos-there/
  dev_url: https://github.com/twsl/whos-there

extra:
  recipe-maintainers:
    - twsl
    - sugatoray
